# Generated by Django 2.0.5 on 2018-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_content', models.CharField(max_length=200)),
                ('item_done', models.BooleanField()),
            ],
        ),
    ]
