# Generated by Django 2.0.5 on 2018-09-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_done',
            new_name='done',
        ),
    ]
